version: '3'
services:
  db:
    build:
      dockerfile: ./docker/db/Dockerfile
      context: .
    restart: always
    ports:
      - "33666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: holidayextras
      MYSQL_USER: holidayextras
      MYSQL_PASSWORD: password
  web:
    build: 
      dockerfile: ./docker/web/Dockerfile
      context: .
    ports:
      - "1337:1337"
    depends_on:
      - "db"
    environment:
      WAIT_HOSTS: db:3306