module.exports = {
	REQUESTED_RESOURCE_NOT_FOUND: "REQUESTED_RESOURCE_NOT_FOUND",
	MODEL_FIND_ERROR: "MODEL_FIND_ERROR",
	MODEL_SAVE_ERROR: "MODEL_SAVE_ERROR",
	MODEL_VALIDATION_ERROR: "MODEL_VALIDATION_ERROR",
	GENERIC_SQL_ERROR: "GENERIC_SQL_ERROR",
	GENERIC_ERROR: "GENERIC_ERROR"
};